### ISSUE TITLE
Move Fitbit import to own oauth2 project

### ISSUE THREAD

**Issue by gedankenstuecke** [OpenHumans/open-humans#746]
https://github.com/mcescalante/oh-fitbit-integration

**Todo**
- [x] OH & Fitbit tokens
- [x] Pull Fitbit data (same as legacy integration)
- [x] Deploy on Heroku and make OH project ready for members
- [x] Write token import script
- [x] Retrieve data and put in OH

Finish data processing:
- [x] partial data import -> fix weekly/year data that's partially
- [x] write method to get/refresh access tokens from Fitbit
- [x] write periodic update task
- [ ] set up heroku scheduler

**Ops/Deployment**
- [x] Retire legacy app (Mad)
- [x] Get current refresh tokens (Mad)
- [x] Import newly created tokens into standalone project
- [x] Shutdown legacy integration (Mad)

**Comment by mcescalante** [comment]
I'll keep the top post in this issue updated as I go 😄

**Comment by mcescalante** [comment]
Done:

- Fetch fitbit data
- Upload fitbit data to OH via celery task
- Refactor entire application from py2 django1 to py3 django2
- Add rate limiting 
- Move celery from RabbitMQ (amqp) to Redis
- Deployed integration (URL coming soon, finishing TLS certificate setup)

We also all agreed that any new functionality (intraday data, vizualizations) should be released as a phase 2 and that the focus should be deploying a standalone clone of the existing integration before adding more.

Up next:
- Scheduled data updates
- Finalize deployment
- Start with existing token regeneration for standalone project

**Comment by mcescalante** [comment]
Just deployed a replacement, and this should close the issue! Check out our further development https://github.com/OpenHumans/oh-fitbit-integration or check the integration itself http://oh-fitbit-integration.herokuapp.com/
