### ISSUE TITLE
Create Microsoft Healthvault oauth2 project

### ISSUE THREAD

**Issue by BenjaminHCCarr** [OpenHumans/open-humans#750]
https://github.com/BenjaminHCCarr/oh-mshealthvault-source

### Todo
- [ ] Make `pyhealthvault` work, as known working python implementation
- [ ] Make API connection to `MS Healthvault` from OH oauth2 project
- [ ] Connect `OH` & `MSHV` Health tokens
- [ ] allow subselection of data
- [ ] Pull `MS Healthvault` data
- [ ] Upload file(s) to OH user/project
- [ ] Visualizations in new app

### Ops/Deployment
- [ ] Deploy staging project
- [ ] Deploy the formal project

**Comment by BenjaminHCCarr** [comment]
Rebased off of https://github.com/OpenHumans/OpenHumans/oh-data-demo-template

**Comment by brierjon** [comment]
Either this project needs to be accelerated or can be closed due to HealthVault announcing it is shutting down.

> As of November 20, 2019, HealthVault will no longer be supported. Please see the notice you may have received. - https://www.healthvault.com/en-us/

**Comment by BenjaminHCCarr** [comment]
> Either this project needs to be accelerated or can be closed due to HealthVault announcing it is shutting down.
> 
> > As of November 20, 2019, HealthVault will no longer be supported. Please see the notice you may have received. - https://www.healthvault.com/en-us/

Having talked with the core team there is no way to archive the data at Open Humans, and none of the proposed options from MS are a good fit. So sadly this will likely end without being implemented.
