### ISSUE TITLE
Create Google Fit oauth2 project

### ISSUE THREAD

**Issue by BenjaminHCCarr** [OpenHumans/open-humans#752]
https://github.com/BenjaminHCCarr/oh-data-google-fit

### Todo
Use Google Fit REST API as described here: https://developers.google.com/fit/rest/

---

### Code I am using as examples:

 `python`: `chewfit`: https://github.com/xchewtoyx/chewfit
 `ruby`: `fitexplorer`: https://github.com/zorfling/fitexplorer
 `php`: `google-fit-php`: https://packagist.org/packages/ljpc/google-fit-php
 Google Fit REST API Samples
    - https://github.com/googlesamples/android-fit/
    - https://developers.google.com/fit/rest/v1/running-examples

---

- [ ] Get `python`: `chewfit` to work outside of sandbox: https://github.com/xchewtoyx/chewfit
- [ ] Make API connection to `Google Fit` from OH oauth2 project
- [ ] Connect `OH` & `GFit` Health tokens
     - [ ]  allow subselection of data
- [ ] Pull `Google Fit` data
- [ ] Upload file(s) to OH user/project
- [ ] Visualizations in new app

### Ops/Deployment
- [ ] Deploy staging project
 - [ ] Deploy the formal project

**Comment by madprime** [comment]
Closing as obsolete/done. (This was completed by @carolinux.)
